name: Build & Deploy Flutter Web to docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # needed to push changes back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: flutter pub get
        run: flutter pub get

      - name: Build Web (for GitHub Pages in /portfolio)
        run: flutter build web --release --base-href /portfolio/

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -R build/web/* docs/
          # helps Pages ignore Jekyll processing
          touch docs/.nojekyll

      # Automatically commit the updated docs/ back to main
      - name: Commit & push docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update docs (GitHub Actions)"
          file_pattern: docs/**

