name: Build & Deploy Flutter Web to docs

on:
  push:
    branches: [main]
    paths:
      - "lib/**"
      - "web/**"
      - "assets/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "!docs/**"          # ignore docs changes so we don't infinite-loop
  workflow_dispatch:        # allow manual runs from Actions tab

permissions:
  contents: write           # needed so the workflow can commit to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"          # or set flutter-version: "3.22.x" if you want a fixed one

      - name: Flutter version
        run: flutter --version

      - name: Get packages
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href /portfolio/

      - name: Move build to docs
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r build/web/* docs/
          # SPA fallback so direct URLs work on GitHub Pages
          cp docs/index.html docs/404.html

      - name: Commit & push docs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: deploy web to docs [skip ci]"
            git push
          fi
